import { Inter, Roboto, Poppins } from 'next/font/google'
import './globals.css'
import Footer from '@/components/footer/Footer'
import Navbar from '@/components/navbar/Navbar'
import { ThemeProvider } from '@/context/ThemeContext'

const poppins = Poppins({ subsets: ['latin'], weight: [ '300','400','500','600', '700'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     
      <body className={poppins.className}>
        <ThemeProvider>
        <div className='container'>
      <Navbar />
        {children}
        <Footer />
        </div>
        </ThemeProvider>
        </body>
       
        
    </html>
  )
}
